### ISSUE TITLE
Admission controller errors when upgrade from 1.12 to 1.16

### ISSUE THREAD

**Issue by xjtustt** [kubernetes-sigs/apiserver-builder-alpha#500]
I am new to apiserver-boot.

In my current project I use apiserver-boot to build a apiserver-aggregation to extend a APIService.
Previously I use apiserver-boot v1.12 to generate code and it works well.

But recently I want to upgrade the apiserver-boot to v1.16 to re-generate code structure but encountered some `admission controller errors`. 

My steps are listed below:

1. `apiserver-boot init repo --domain <my-domain>`
2. `apiserver-boot create group version resource --group <my-group> --version <my-version> --kind <my-kind>`
    - `Create Resource [y/n]` -> `y`
    - `Create Controller [y/n]` -> `n`
    - `Create Admission Controller [y/n]` -> `n`
    - the reason why I did not create controller and admission controller is because I only need to use Get/List method to query the new resource
    - then I follow this [doc](https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/docs/adding_custom_rest.md) to update the *_types.go and also add a *_rest.go.
3. `operator-sdk build container --image <image-name>`(or create a Dockerfile to use `docker build .`)
4. then use the image built in step3 in my pod, when the apiserver binary starts, I see some errors like this:

```
I0428 03:40:16.262234       1 serving.go:312] Generated self-signed cert (/tmp/apiserver.crt, /tmp/apiserver.key)
I0428 03:40:16.262411       1 start.go:354] loading in-cluster loopback client...
W0428 03:40:16.888421       1 start.go:309] skip admission controller initialization because no custom admission controllers are installed
I0428 03:40:16.890272       1 plugins.go:158] Loaded 2 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,MutatingAdmissionWebhook.
I0428 03:40:16.890305       1 plugins.go:161] Loaded 1 validating admission controller(s) successfully in the following order: ValidatingAdmissionWebhook.
E0428 03:40:16.935915       1 pathrecorder.go:107] registered "/healthz/etcd" from goroutine 1 [running]:
runtime/debug.Stack(0x19d8420, 0xc000518ed0, 0xc000308050)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc000112310, 0xc000308050, 0xd)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:109 +0x86
github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).Handle(0xc000112310, 0xc000308050, 0xd, 0x203ed60, 0xc0005081d0)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:173 +0xac
github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server/healthz.InstallPathHandler(0x203c3e0, 0xc000112310, 0x1c6f349, 0x8, 0xc000503580, 0x5, 0x8)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:127 +0x39d
github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server/healthz.InstallHandler(...)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:93
github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).installHealthz(0xc0001874a0)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server/healthz.go:96 +0xda
github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc0001874a0, 0xc0000e6b20)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:292 +0x5c
github.ibm.com/IBMPrivateCloud/aaa/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server.(*ServerOptions).RunServer(0xc000674120, 0xc00005c360, 0x1c6a59d, 0x3, 0x1c6a2e4, 0x2, 0x0, 0x0, 0x0, 0x1c6b047, ...)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server/start.go:411 +0x482
github.ibm.com/IBMPrivateCloud/aaa/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server.NewCommandStartServer.func1(0xc000338d80, 0xc0002ba160, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server/start.go:185 +0xf1
github.ibm.com/IBMPrivateCloud/aaa/vendor/github.com/spf13/cobra.(*Command).execute(0xc000338d80, 0xc0000c4160, 0x2, 0x2, 0xc000338d80, 0xc0000c4160)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/github.com/spf13/cobra/command.go:599 +0x3e2
github.ibm.com/IBMPrivateCloud/aaa/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000338d80, 0xc000096120, 0x203d3a0, 0xc0000e6008)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/github.com/spf13/cobra/command.go:689 +0x2bc
github.ibm.com/IBMPrivateCloud/aaa/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/github.com/spf13/cobra/command.go:648
github.ibm.com/IBMPrivateCloud/aaa/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server.StartApiServerWithOptions(0xc000689ed0, 0xc0003d0370, 0xc000488de0)
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server/start.go:119 +0x2cc
main.main()
	/go/src/github.ibm.com/IBMPrivateCloud/aaa/cmd/apiserver/main.go:27 +0x10b
I0428 03:40:16.937408       1 secure_serving.go:123] Serving securely on [::]:7443
E0428 03:40:16.947975       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.MutatingWebhookConfiguration: unknown (get mutatingwebhookconfigurations.admissionregistration.k8s.io)
E0428 03:40:16.948951       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.ValidatingWebhookConfiguration: unknown (get validatingwebhookconfigurations.admissionregistration.k8s.io)
E0428 03:40:16.949002       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Namespace: unknown (get namespaces)
```

The Get/List function works well but I want to make clear why these errors happen, I have some questions here:
1. I didn't create the admission controller but why the logs shows `Loaded 2 mutating admission controller(s) successfully` and `Loaded 1 validating admission controller(s) successfully`. I think this caused the following errors
2. What is `registered "/healthz/etcd" from goroutine` used for? When use apiserver-boot v1.12, I have not see this log? And looks the register failed with some errors.
3. Why there are lots of `Failed to watch *v1beta1.MutatingWebhookConfiguration` these kind of errors?

**Comment by yue9944882** [comment]
thank you for reporting this, as a workaround, can you try adding the following flags to your apiserver?

`--disable-admission-plugins= NamespaceLifecycle,MutatingAdmissionWebhook,ValidatingAdmissionWebhook`

**Comment by xjtustt** [comment]
@yue9944882 After I add the flags, the errors disappears. Thank you!
