### ISSUE TITLE
pathrecorder.go /healthz/etcd error

### ISSUE THREAD

**Issue by smartkuk** [kubernetes-sigs/apiserver-builder-alpha#511]
Hi~ I'm back... I have some error logs.

When I run the extended API server I get the following error:

I tried because [issue #500] is similar to what I'm going through, but I get the same error.

Of course, there is nothing about the extended API server as [issue #500]. But I want to get rid of this error, or implement a source I don't know to get rid of the error.

***Can you guide(any options, flags, urls, sources) me?***

starting error log:

```go
E0708 13:57:34.289620   51086 pathrecorder.go:107] registered "/healthz/etcd" from goroutine 1 [running]:
runtime/debug.Stack(0x2806c60, 0xc00040cd50, 0xc00035fb80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc0002760e0, 0xc00035fb80, 0xd)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:109 +0x86
smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).Handle(0xc0002760e0, 0xc00035fb80, 0xd, 0x2e98ca0, 0xc000d51610)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:173 +0x84
smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server/healthz.InstallPathHandler(0x2e95460, 0xc0002760e0, 0x2aab289, 0x8, 0xc0007dcb80, 0x4, 0x4)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:127 +0x39d
smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server/healthz.InstallHandler(...)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:93
smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).installHealthz(0xc000456000)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server/healthz.go:96 +0xc7
smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc000456000, 0xc0007d4138)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:292 +0x5c
smartkuk.io/smartkuk-apiserver/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server.(*ServerOptions).RunServer(0xc0007fe960, 0xc0000601e0, 0x2aa650a, 0x3, 0x2aa6239, 0x2, 0x0, 0x0, 0x0, 0x2aa6fbe, ...)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server/start.go:411 +0x468
smartkuk.io/smartkuk-apiserver/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server.NewCommandStartServer.func1(0xc00031f680, 0xc00024a000, 0x0, 0xe, 0x0, 0x0)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server/start.go:185 +0xf1
smartkuk.io/smartkuk-apiserver/vendor/github.com/spf13/cobra.(*Command).execute(0xc00031f680, 0xc00004e100, 0xe, 0xe, 0xc00031f680, 0xc00004e100)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/github.com/spf13/cobra/command.go:599 +0x3d5
smartkuk.io/smartkuk-apiserver/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00031f680, 0xc0000de240, 0x2e97020, 0xc000010018)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/github.com/spf13/cobra/command.go:689 +0x2bc
smartkuk.io/smartkuk-apiserver/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/github.com/spf13/cobra/command.go:648
smartkuk.io/smartkuk-apiserver/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server.StartApiServerWithOptions(0xc0008ebef8, 0xc0007d4070, 0xc0007d4068)
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server/start.go:119 +0x2cc
main.main()
	/Users/smartkuk/Documents/go_workspace/src/smartkuk.io/smartkuk-apiserver/cmd/apiserver/main.go:25 +0x10b
```

apiserver-boot binary version:

```sh
$ apiserver-boot version
I0708 14:06:18.335799   51825 version.go:57] Version: version.Version{ApiserverBuilderVersion:"v1.16.alpha.2", KubernetesVendor:"kubernetes-1.16.0", GitCommit:"fbc6092eb4d7e58d690516620653fe5e34d194ac", BuildDate:"2020-03-11-18:33:45", GoOs:"darwin", GoArch:"amd64"}
```

run command line:

```sh
bin/apiserver \
  --authorization-kubeconfig=./sample/kubeconfig \
  --etcd-servers="https://${MINIKUBE_ETCD_SERVER_IP}:${MINIKUBE_ETCD_SERVER_PORT}" \
  --etcd-cafile=./config/certificates/minikube-etcd-ca.crt \
  --etcd-certfile=./config/certificates/minikube-etcd-client.crt \
  --etcd-keyfile=./config/certificates/minikube-etcd-client.key \
  --tls-cert-file=./config/certificates/apiserver.crt \
  --tls-private-key-file=./config/certificates/apiserver.key \
  --requestheader-allowed-names=front-proxy-client \
  --requestheader-client-ca-file=./config/certificates/front-proxy-ca.crt \
  --requestheader-extra-headers-prefix=X-Remote-Extra- \
  --requestheader-group-headers=X-Remote-Group \
  --requestheader-username-headers=X-Remote-User \
  --secure-port=8443
```

[issue #500]: https://github.com/kubernetes-sigs/apiserver-builder-alpha/issues/500

**Comment by smartkuk** [comment]
I haven't had an answer for too long, so I'll add an additional explanation... I'm running my extended API server outside the Kubernetes cluster, not inside. Even if I look at the error log and follow the source, I don't know how to make it skip that url path without reading it.

Anyone can help?

The log contents and shell script below are the logs displayed above the log above. The same is true even if the apiserver-builder-alpha version is raised to 1.17.

```sh
go build -o bin/apiserver cmd/apiserver/main.go
bin/apiserver \
  --authorization-kubeconfig=./sample/kubeconfig \
  --etcd-servers="https://${MINIKUBE_ETCD_SERVER_IP}:${MINIKUBE_ETCD_SERVER_PORT}" \
  --etcd-cafile=./config/certificates/minikube-etcd-ca.crt \
  --etcd-certfile=./config/certificates/minikube-etcd-client.crt \
  --etcd-keyfile=./config/certificates/minikube-etcd-client.key \
  --tls-cert-file=./config/certificates/apiserver.crt \
  --tls-private-key-file=./config/certificates/apiserver.key \
  --requestheader-allowed-names=front-proxy-client \
  --requestheader-client-ca-file=./config/certificates/front-proxy-ca.crt \
  --requestheader-extra-headers-prefix=X-Remote-Extra- \
  --requestheader-group-headers=X-Remote-Group \
  --requestheader-username-headers=X-Remote-User \
  --secure-port=8443
```

```go
I0821 10:59:44.044147    6388 scale_application_rest.go:163] init
I0821 10:59:44.044284    6388 scale_application_rest.go:169] register
I0821 10:59:44.047288    6388 start.go:359] loading in-cluster loopback client...
W0821 10:59:44.047304    6388 start.go:250] attempting to instantiate loopback client but failed: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
W0821 10:59:44.347272    6388 authentication.go:267] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
I0821 10:59:44.350947    6388 start.go:325] skip admission controller initialization because `--kubeconfig` is not specified
I0821 10:59:44.352555    6388 client.go:361] parsed scheme: "endpoint"
I0821 10:59:44.352592    6388 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://192.168.64.2:2379 0  <nil>}]
I0821 10:59:44.353400    6388 once.go:66] CPU time info is unavailable on non-linux or appengine environment.
I0821 10:59:44.359911    6388 client.go:361] parsed scheme: "endpoint"
I0821 10:59:44.359929    6388 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://192.168.64.2:2379 0  <nil>}]
I0821 10:59:44.367297    6388 client.go:361] parsed scheme: "endpoint"
I0821 10:59:44.367319    6388 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://192.168.64.2:2379 0  <nil>}]
I0821 10:59:44.374565    6388 scale_application_rest.go:153] Started New()
I0821 10:59:44.374582    6388 scale_application_rest.go:155] Finished New()
I0821 10:59:44.396574    6388 scale_application_rest.go:153] Started New()
I0821 10:59:44.396592    6388 scale_application_rest.go:155] Finished New()
```

**Comment by smartkuk** [comment]
I've figured out how to avoid errors, but I ask @yue9944882 in charge(maybe) of the project:

In k8s.io/apiserver/pkg/server/options/etcd.go source, it is executed on lines [func ApplyTo] and [func ApplyWithStorageFactoryTo] and creates and adds a &healthzCheck{name, check} object with a duplicate "etcd" name.

At this time, If ```delegated-auth=false``` is specified, the error is avoided by processing the checker not to be added through line [func ApplyWithStorageFactoryTo]. Is it possible to avoid the error like this?

Or do I have to edit other sources?

Or is it a bug to add the "etcd" name twice?

[func ApplyTo]: https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/apiserver/pkg/server/options/etcd.go#L181

[func ApplyWithStorageFactoryTo]: https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/staging/src/k8s.io/apiserver/pkg/server/options/etcd.go#L192

**Comment by yue9944882** [comment]
@smartkuk sry for the delayed response, i will take a look at this soon later!
