### ISSUE TITLE
v2.0.0-beta.0 kubectl create object fail ( no openapi endpoint? )

### ISSUE THREAD

**Issue by chinglinwen** [kubernetes-sigs/apiserver-builder-alpha#593]
It seems that apiserver-builder-alpha v2.beta.0's api(standalone debug mode) doesn't provide openapi URI anymore( it does with v1.18.0),  currently, I found that it cause kubectl fail to create object ( using code to create object is ok ).

```
$ kubectl apply -f bee.yaml -v7
I0430 16:23:37.772170 3656155 loader.go:379] Config loaded from file:  kubeconfig
I0430 16:23:37.773135 3656155 round_trippers.go:422] GET https://localhost:9443/openapi/v2?timeout=32s
I0430 16:23:37.773150 3656155 round_trippers.go:429] Request Headers:
I0430 16:23:37.773157 3656155 round_trippers.go:433]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0430 16:23:37.773165 3656155 round_trippers.go:433]     User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/af46c47
I0430 16:23:37.773173 3656155 round_trippers.go:433]     Authorization: Basic <masked>
I0430 16:23:37.780217 3656155 round_trippers.go:448] Response Status: 404 Not Found in 7 milliseconds
I0430 16:23:37.792911 3656155 round_trippers.go:422] GET https://localhost:9443/swagger-2.0.0.pb-v1?timeout=32s
I0430 16:23:37.792929 3656155 round_trippers.go:429] Request Headers:
I0430 16:23:37.792936 3656155 round_trippers.go:433]     Accept: application/json, */*
I0430 16:23:37.792943 3656155 round_trippers.go:433]     User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/af46c47
I0430 16:23:37.792951 3656155 round_trippers.go:433]     Authorization: Basic <masked>
I0430 16:23:37.793617 3656155 round_trippers.go:448] Response Status: 404 Not Found in 0 milliseconds
I0430 16:23:37.801323 3656155 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "unknown"
      }
    ]
  },
  "code": 404
}]
F0430 16:23:37.801366 3656155 helpers.go:115] Error from server (NotFound): the server could not find the requested resource
goroutine 1 [running]:
```
I tried with kubectlv1.21.0 apply -f bee.yaml -v7, same error

<details>
<summary>apply error logs</summary>

$ kubectl apply -f node.yaml  -v9
I0430 15:44:09.662285 3625240 loader.go:379] Config loaded from file:  kubeconfig
I0430 15:44:09.663288 3625240 round_trippers.go:425] curl -k -v -XGET  -H "Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf" -H "User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/af46c47" -H "Authorization: Basic <masked>" 'https://localhost:9443/openapi/v2?timeout=32s'
I0430 15:44:09.672461 3625240 round_trippers.go:445] GET https://localhost:9443/openapi/v2?timeout=32s 404 Not Found in 9 milliseconds
I0430 15:44:09.672482 3625240 round_trippers.go:451] Response Headers:
I0430 15:44:09.672489 3625240 round_trippers.go:454]     Content-Length: 714
I0430 15:44:09.672495 3625240 round_trippers.go:454]     Date: Fri, 30 Apr 2021 07:44:09 GMT
I0430 15:44:09.672500 3625240 round_trippers.go:454]     Cache-Control: no-cache, private
I0430 15:44:09.672506 3625240 round_trippers.go:454]     Content-Type: application/json
I0430 15:44:09.676772 3625240 request.go:1107] Response Body: {
  "paths": [
    "/apis",
    "/apis/operator.example.com",
    "/apis/operator.example.com/v1alpha1",
    "/healthz",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/max-in-flight-filter",
    "/healthz/poststarthook/start-sample-server-informers",
    "/livez",
    "/livez/etcd",
    "/livez/log",
    "/livez/ping",
    "/livez/poststarthook/max-in-flight-filter",
    "/livez/poststarthook/start-sample-server-informers",
    "/metrics",
    "/readyz",
    "/readyz/etcd",
    "/readyz/log",
    "/readyz/ping",
    "/readyz/poststarthook/max-in-flight-filter",
    "/readyz/poststarthook/start-sample-server-informers",
    "/readyz/shutdown",
    "/version"
  ]
}
I0430 15:44:09.679434 3625240 round_trippers.go:425] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/af46c47" -H "Authorization: Basic <masked>" 'https://localhost:9443/swagger-2.0.0.pb-v1?timeout=32s'
I0430 15:44:09.680332 3625240 round_trippers.go:445] GET https://localhost:9443/swagger-2.0.0.pb-v1?timeout=32s 404 Not Found in 0 milliseconds
I0430 15:44:09.680352 3625240 round_trippers.go:451] Response Headers:
I0430 15:44:09.680360 3625240 round_trippers.go:454]     Content-Type: application/json
I0430 15:44:09.680366 3625240 round_trippers.go:454]     Content-Length: 714
I0430 15:44:09.680371 3625240 round_trippers.go:454]     Date: Fri, 30 Apr 2021 07:44:09 GMT
I0430 15:44:09.680377 3625240 round_trippers.go:454]     Cache-Control: no-cache, private
I0430 15:44:09.682805 3625240 request.go:1107] Response Body: {
  "paths": [
    "/apis",
    "/apis/operator.example.com",
    "/apis/operator.example.com/v1alpha1",
    "/healthz",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/max-in-flight-filter",
    "/healthz/poststarthook/start-sample-server-informers",
    "/livez",
    "/livez/etcd",
    "/livez/log",
    "/livez/ping",
    "/livez/poststarthook/max-in-flight-filter",
    "/livez/poststarthook/start-sample-server-informers",
    "/metrics",
    "/readyz",
    "/readyz/etcd",
    "/readyz/log",
    "/readyz/ping",
    "/readyz/poststarthook/max-in-flight-filter",
    "/readyz/poststarthook/start-sample-server-informers",
    "/readyz/shutdown",
    "/version"
  ]
}
I0430 15:44:09.687017 3625240 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "unknown"
      }
    ]
  },
  "code": 404
}]
F0430 15:44:09.687063 3625240 helpers.go:115] Error from server (NotFound): the server could not find the requested resource
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc0000ca001, 0xc0006440d0, 0x7d, 0xce)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2a6c040, 0xc000000003, 0x0, 0x0, 0xc000626d90, 0x284c16b, 0xa, 0x73, 0x40e200)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x2a6c040, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc000a07040, 0x1, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1488
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc0002f8d20, 0x4e, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x26e
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x1cebe00, 0xc00055e6e0, 0x1bb70f8)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x945
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/apply.NewCmdApply.func1(0xc00063a2c0, 0xc0004662d0, 0x0, 0x3)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/apply/apply.go:177 +0x73
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00063a2c0, 0xc0004662a0, 0x3, 0x3, 0xc00063a2c0, 0xc0004662a0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f8b00, 0xc0000cc120, 0xc0000d0000, 0x5)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 9 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1bb7018, 0x1cec100, 0xc0000fc000, 0x1, 0xc0000a4b40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1bb7018, 0x12a05f200, 0x0, 0x1, 0xc0000a4b40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1bb7018, 0x12a05f200, 0xc0000a4b40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x2aeab1b6f498, 0x72, 0x1cef1c0)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000971d18, 0x72, 0x1cef100, 0x2878610, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000971d00, 0xc0005a7800, 0xb19, 0xb19, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc000971d00, 0xc0005a7800, 0xb19, 0xb19, 0x203000, 0x652cfb, 0xc000548160)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0000ca098, 0xc0005a7800, 0xb19, 0xb19, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc00054b4a0, 0xc0005a7800, 0xb19, 0xb19, 0x2e4, 0xaf0, 0xc00068f710)
        /usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc000548280, 0x1ceab00, 0xc00054b4a0, 0x40b645, 0x18e4ea0, 0x1a4d560)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000548000, 0x1ced5a0, 0xc0000ca098, 0x5, 0xc0000ca098, 0x2d3)
        /usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000548000, 0x0, 0x0, 0xc00068fd18)
        /usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc000548000, 0xc000571000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc00030c9c0, 0xc00056a1f8, 0x9, 0x9, 0xc00068fd18, 0x1bb7e00, 0x967a4b)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1cea920, 0xc00030c9c0, 0xc00056a1f8, 0x9, 0x9, 0x9, 0xc0000a6050, 0x0, 0x1cead20)
        /usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader(0xc00056a1f8, 0x9, 0x9, 0x1cea920, 0xc00030c9c0, 0x0, 0x0, 0xc00068fdd0, 0x46b325)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x89
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc00056a1c0, 0xc0005470b0, 0x0, 0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00068ffa8, 0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc000001b00)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5
</details>

**Comment by chinglinwen** [comment]
after adding generate openapi ( as it does with v1.18.0 )
```
openapi-gen --input-dirs apidemov2beta/pkg/apis/operator/v1alpha1 -o $GOPATH/src --go-header-file hack/boilerplate.go.txt -i k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/api/resource,k8s.io/apimachinery/pkg/version,k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/util/intstr,k8s.io/api/core/v1,k8s.io/api/apps/v1 --report-filename violations.report --output-package apidemov2beta/pkg/openapi
```
and add `WithOpenAPIDefinitions("api", "v1alpha1", openapi.GetOpenAPIDefinitions).` to apiserver, it now works for creating object from kubectl command.

```
[wen@k01v k8slocal apidemov2beta]$ kubectl apply -f bee.yaml  -v7
I0512 15:10:07.467450  986312 loader.go:379] Config loaded from file:  kubeconfig
I0512 15:10:07.468569  986312 round_trippers.go:422] GET https://10.249.216.68:9443/openapi/v2?timeout=32s
I0512 15:10:07.468584  986312 round_trippers.go:429] Request Headers:
I0512 15:10:07.468591  986312 round_trippers.go:433]     User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/af46c47
I0512 15:10:07.468600  986312 round_trippers.go:433]     Authorization: Basic <masked>
I0512 15:10:07.468616  986312 round_trippers.go:433]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0512 15:10:07.481045  986312 round_trippers.go:448] Response Status: 200 OK in 12 milliseconds
I0512 15:10:07.553539  986312 round_trippers.go:422] GET https://10.249.216.68:9443/apis/operator.example.com/v1alpha1/nodes/node1
I0512 15:10:07.553574  986312 round_trippers.go:429] Request Headers:
I0512 15:10:07.553587  986312 round_trippers.go:433]     Accept: application/json
I0512 15:10:07.553598  986312 round_trippers.go:433]     User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/af46c47
I0512 15:10:07.553611  986312 round_trippers.go:433]     Authorization: Basic <masked>
I0512 15:10:07.555651  986312 round_trippers.go:448] Response Status: 404 Not Found in 2 milliseconds
I0512 15:10:07.556478  986312 round_trippers.go:422] POST https://10.249.216.68:9443/apis/operator.example.com/v1alpha1/nodes?fieldManager=kubectl-client-side-apply
I0512 15:10:07.556492  986312 round_trippers.go:429] Request Headers:
I0512 15:10:07.556499  986312 round_trippers.go:433]     User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/af46c47
I0512 15:10:07.556508  986312 round_trippers.go:433]     Authorization: Basic <masked>
I0512 15:10:07.556514  986312 round_trippers.go:433]     Accept: application/json
I0512 15:10:07.556521  986312 round_trippers.go:433]     Content-Type: application/json
I0512 15:10:07.570221  986312 round_trippers.go:448] Response Status: 201 Created in 13 milliseconds
node.operator.example.com/node1 created
I0512 15:10:07.570423  986312 apply.go:396] Running apply post-processor function
[wen@k01v k8slocal apidemov2beta]$ kubectl get nodes
NAME    CREATED AT
node1   2021-05-12T07:10:07Z
[wen@k01v k8slocal apidemov2beta]$ kubectl get nodes -v7
I0512 15:10:15.997522  986455 loader.go:379] Config loaded from file:  kubeconfig
I0512 15:10:15.999916  986455 round_trippers.go:422] GET https://10.249.216.68:9443/apis/operator.example.com/v1alpha1/nodes?limit=500
I0512 15:10:15.999933  986455 round_trippers.go:429] Request Headers:
I0512 15:10:15.999941  986455 round_trippers.go:433]     Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json
I0512 15:10:15.999948  986455 round_trippers.go:433]     User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/af46c47
I0512 15:10:15.999956  986455 round_trippers.go:433]     Authorization: Basic <masked>
I0512 15:10:16.010300  986455 round_trippers.go:448] Response Status: 200 OK in 10 milliseconds
NAME    CREATED AT
node1   2021-05-12T07:10:07Z
```
